version: '3'

services:
  local-spark:
    image: local-spark
    container_name: local-spark
    build:
      context: ./
      dockerfile: ./containers/spark/Dockerfile
    environment:
      METADATA_DRIVERNAME: postgresql
      METADATA_HOST: metadata
      METADATA_PORT: '5432'
      METADATA_USERNAME: sdeuser
      METADATA_PASSWORD: sdepassword
      METADATA_DATABASE: metadatadb
    hostname: localhost
    ports:
      - "4040:4040"
    volumes:
      - ./adventureworks:/opt/spark/work-dir/adventureworks

  minio:
    image: 'minio/minio:RELEASE.2023-07-21T21-12-44Z'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

  metadata:
    image: postgres:15
    container_name: metadata
    environment:
      POSTGRES_USER: sdeuser
      POSTGRES_PASSWORD: sdepassword
      POSTGRES_DB: metadatadb
    ports:
      - "5432:5432"

  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000 minio minio123; /usr/bin/mc rm -r --force myminio/tpch; /usr/bin/mc mb myminio/tpch; /usr/bin/mc policy download myminio/tpch; exit 0; "
